sudo: false
services:
  - redis-server
language: csharp
dist: trusty
mono: none
dotnet: 1.0.1
before_script:
  - dotnet restore -v Minimal
script:
  - dotnet build "Hangfire.Redis.Tests" -c Debug -f netcoreapp2.0
  - dotnet test "Hangfire.Redis.Tests/Hangfire.Redis.Tests.csproj" -c Debug -f netcoreapp2.0